image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: ReversiRestApi.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\NUnitTestProjectReversiSpel\bin\Debug\NUnitTestProjectReversiSpel.dll -noshadow" -filter:"+[ReversiRestApi*]* -[NUnitTestProjectReversiSpel*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml
