name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger "trx;logfilename=testResults.trx"
    - name: Test Reporter
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with: 
        artifact: test-results
        name: NUNIT Tests
        path: '*.trx'
        reporter: dotnet-trx
        fail-on-error: 'true'
        fail-on-empty: 'true'
